// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMMNcUZex_S__cP51W3q9r_K2DgeMG0do',
    appId: '1:868242363057:web:51cf55c2c8d39dcdefc890',
    messagingSenderId: '868242363057',
    projectId: 'madfinalweekpro',
    authDomain: 'madfinalweekpro.firebaseapp.com',
    storageBucket: 'madfinalweekpro.firebasestorage.app',
    measurementId: 'G-87W6XKMYPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByeZesB0a4nGyVbpBbECWLa4HBzB8K37A',
    appId: '1:868242363057:android:ed14639f4c49ab57efc890',
    messagingSenderId: '868242363057',
    projectId: 'madfinalweekpro',
    storageBucket: 'madfinalweekpro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR_EUyr7mx0C-nMw_l2jI-wxB4BnZAC_Y',
    appId: '1:868242363057:ios:ed36a8d2aeb0407fefc890',
    messagingSenderId: '868242363057',
    projectId: 'madfinalweekpro',
    storageBucket: 'madfinalweekpro.firebasestorage.app',
    iosBundleId: 'com.example.finalwe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR_EUyr7mx0C-nMw_l2jI-wxB4BnZAC_Y',
    appId: '1:868242363057:ios:ed36a8d2aeb0407fefc890',
    messagingSenderId: '868242363057',
    projectId: 'madfinalweekpro',
    storageBucket: 'madfinalweekpro.firebasestorage.app',
    iosBundleId: 'com.example.finalwe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMMNcUZex_S__cP51W3q9r_K2DgeMG0do',
    appId: '1:868242363057:web:eb5a81fbeaa70f81efc890',
    messagingSenderId: '868242363057',
    projectId: 'madfinalweekpro',
    authDomain: 'madfinalweekpro.firebaseapp.com',
    storageBucket: 'madfinalweekpro.firebasestorage.app',
    measurementId: 'G-VJ13FXT4RP',
  );
}
